version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: impamp3:latest
    container_name: impamp3-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3025}:3000"  # Map to host port specified by HOST_PORT env var (default: 3025)
    environment:
      - NODE_ENV=production
      # Add any additional environment variables here
    
  # Development service with hot-reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: impamp3-dev:latest
    container_name: impamp3-dev
    profiles: ["development"]  # Only start when the "development" profile is active
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${DEV_PORT:-3000}:3000"  # Map to host port specified by DEV_PORT env var (default: 3002)
    environment:
      - NODE_ENV=development
    command: npm run dev
